#!/usr/bin/php
<?php
/**
 * SyDES - Lightweight CMF for a simple sites with SQLite database
 *
 * @package   SyDES
 * @copyright 2011-2017, ArtyGrand <artygrand.ru>
 * @license   GNU GPL v3 or later; see LICENSE
 */
if (PHP_SAPI != 'cli') {
    exit;
}

require __DIR__.'/vendor/autoload.php';

$app = new App\Console\Kernel();

$app->run(is_array($argv) ? $argv : [], $argc);
