#!/usr/bin/php
<?php
/**
 * @link      https://github.com/sydes/sydes
 * @copyright 2011-2017, ArtyGrand <artygrand.ru>
 * @license   GNU GPL v3 or later; see LICENSE
 */

if (PHP_SAPI != 'cli') {
    exit(1);
}

$container = require __DIR__.'/system/bootstrap.php';

if (!class_exists('Silly\Application')) {
    echo 'Install Silly first. composer require mnapoli/silly';
    exit(1);
}

$app = new Silly\Application('SyDES CLI', 'v1');

$finder = new Sydes\Console\CommandFinder($app, $container);
$finder->find();

$app->run();
